[package]
name = "word"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
env_logger = { version = "0.10", default-features = false }
opencv = "0.93.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
kiddo = "4.2.1"